package dev.fenn.imessage.registration

/**
 * GENERATED FILE — regenerate with /tmp/clearadi-re/gen_p_table.py (session 23); do not
 * hand-edit. Byte-serialised instruction stream of the P-table SSE builder
 * (state+0x6898, 7x256 bytes) inside SignState::sign at 0x17a1381-0x17a20b5,
 * plus the 46 16-byte .rodata const vectors it consumes. The P region is
 * INPUT-DEPENDENT: five body-derived bytes (st[a]^st[b] pairs read by the RM/XRM
 * ops) select one of 256 variants per variable table — the old frozen pTable
 * was the session-20 snapshot, falsified on fresh inputs 2026-10-08.
 *
 * Verified: the serialised program reproduces the unicorn-executed builder
 * byte-exact on the fresh live input (c56d) and on the session-20 capture
 * (NAC-NOTES.md "P region CLOSED").
 */
internal object NacPTable {

    /** program: little-endian i32 words (opcode + operands), see gen_p_table.py. */
    private val prog: IntArray by lazy {
        val b = java.util.Base64.getDecoder().decode(PROG)
        IntArray(b.size / 4) { i ->
            (b[4 * i].toInt() and 0xff) or ((b[4 * i + 1].toInt() and 0xff) shl 8) or
                ((b[4 * i + 2].toInt() and 0xff) shl 16) or (b[4 * i + 3].toInt() shl 24)
        }
    }

    private val consts: Array<ByteArray> by lazy {
        val b = java.util.Base64.getDecoder().decode(CONSTS)
        Array(b.size / 16) { i -> b.copyOfRange(16 * i, 16 * i + 16) }
    }

    private const val PROG = "AAAAAIooAAAAAAAAAwAAAHooAAAIAAAAAQAAAAgAAAABAAAAAgAAAAgAAAAIAAAABQAAAO0AAAAIAAAAAQAAAAgAAAAAAAAABwAAAAAAAAAAAAAACAAAAAAAAAAAAAAACQAAAAAAAAAAAAAAAAAAAAoAAABEAAAAAAAAAA4AAAAHAAAAAQAAAAAAAAAIAAAAAAAAAAAAAAAJAAAAAAAAAAAAAAAAAAAACgAAAEQAAAAAAAAAAAAAAAwAAAAAAAAABwAAAAsAAAAAAAAAAwAAAA0AAAAHAAAAAwAAAAwAAAABAAAABQAAAAsAAAAAAAAABAAAAA0AAAAFAAAABAAAAAwAAAACAAAAAQAAAA8AAAAAAAAAAQAAABIAAAADAAAAAQAAAA8AAAABAAAAAwAAAA8AAAABAAAABAAAABAAAAADAAAAAwAAABAAAAAEAAAABAAAAAwAAAAEAAAAAgAAAA8AAAACAAAAAwAAAA8AAAACAAAABAAAABAAAAAOAAAAAwAAABAAAAAOAAAABAAAABcAAAAAAAAAAwAAABcAAAAQAAAABAAAAAsAAAAAAAAAAwAAABIAAAAFAAAAAwAAAAsAAAAAAAAABAAAABIAAAAGAAAABAAAAA8AAAABAAAAAwAAAA8AAAABAAAABAAAABAAAAADAAAAAwAAABAAAAAEAAAABAAAAA8AAAACAAAAAwAAAA8AAAACAAAABAAAABAAAAAOAAAAAwAAABAAAAAOAAAABAAAABcAAAAgAAAAAwAAABcAAAAwAAAABAAAAAsAAAAAAAAAAwAAABIAAAAHAAAAAwAAAAsAAAAAAAAABAAAABIAAAAIAAAABAAAAA8AAAABAAAAAwAAAA8AAAABAAAABAAAABAAAAADAAAAAwAAABAAAAAEAAAABAAAAA8AAAACAAAAAwAAAA8AAAACAAAABAAAABAAAAAOAAAAAwAAABAAAAAOAAAABAAAABcAAABAAAAAAwAAABcAAABQAAAABAAAAAwAAAAJAAAADwAAAAsAAAAAAAAAAwAAAA0AAAAPAAAAAwAAAAsAAAAAAAAABAAAABIAAAAKAAAABAAAAA8AAAABAAAAAwAAAA8AAAABAAAABAAAABAAAAADAAAAAwAAABAAAAAEAAAABAAAAA8AAAACAAAAAwAAAA8AAAACAAAABAAAABAAAAAOAAAAAwAAABAAAAAOAAAABAAAABcAAABgAAAAAwAAABcAAABwAAAABAAAAAwAAAALAAAADQAAAAsAAAAAAAAAAwAAAA0AAAANAAAAAwAAAAsAAAAAAAAABAAAABIAAAAMAAAABAAAAA8AAAABAAAAAwAAAA8AAAABAAAABAAAABAAAAADAAAAAwAAABAAAAAEAAAABAAAAA8AAAACAAAAAwAAAA8AAAACAAAABAAAABAAAAAOAAAAAwAAABAAAAAOAAAABAAAABcAAACAAAAAAwAAABcAAACQAAAABAAAAAwAAAANAAAADAAAAAsAAAAAAAAAAwAAAA0AAAAMAAAAAwAAAA8AAAABAAAAAwAAABAAAAADAAAAAwAAAA8AAAACAAAAAwAAABAAAAAOAAAAAwAAABcAAACgAAAAAwAAAAwAAAAOAAAACwAAAAsAAAAAAAAAAwAAAA0AAAALAAAAAwAAAA8AAAABAAAAAwAAABAAAAADAAAAAwAAAA8AAAACAAAAAwAAABAAAAAOAAAAAwAAABcAAACwAAAAAwAAAAwAAAAPAAAACgAAAAsAAAAAAAAAAwAAAA0AAAAKAAAAAwAAAA8AAAABAAAAAwAAABAAAAADAAAAAwAAAA8AAAACAAAAAwAAABAAAAAOAAAAAwAAABcAAADAAAAAAwAAAAwAAAAQAAAABgAAAAsAAAAAAAAAAwAAAA0AAAAGAAAAAwAAAA8AAAABAAAAAwAAABAAAAADAAAAAwAAAA8AAAACAAAAAwAAABAAAAAOAAAAAwAAABcAAADQAAAAAwAAAAwAAAARAAAACAAAAAsAAAAAAAAAAwAAAA0AAAAIAAAAAwAAAAwAAAASAAAACQAAAA0AAAAJAAAAAAAAAA8AAAABAAAAAwAAAA8AAAABAAAAAAAAABAAAAADAAAAAwAAABAAAAAAAAAAAAAAAA8AAAACAAAAAwAAAA8AAAACAAAAAAAAABAAAAAOAAAAAwAAABAAAAAOAAAAAAAAABcAAADgAAAAAwAAABcAAADwAAAAAAAAAAAAAAB/KAAAAAAAAAMAAAB/JgAACAAAAAEAAAAAAAAAAQAAAAIAAABBAAAACQAAAAUAAABsAAAACQAAAAEAAAAJAAAAAQAAAAcAAAABAAAAAAAAAAgAAAAAAAAAAAAAAAkAAAAAAAAAAAAAAAAAAAAKAAAARAAAAAAAAAAAAAAAAQAAAAgAAAABAAAABgAAAEEAAAAIAAAAAQAAAAgAAAAAAAAABwAAAAAAAAABAAAACAAAAAEAAAABAAAACQAAAAAAAAABAAAAAQAAAAoAAABEAAAAAQAAAAEAAAAHAAAAAQAAAAIAAAAIAAAAAgAAAAIAAAAJAAAAAAAAAAIAAAACAAAACgAAAEQAAAACAAAADgAAAAwAAAATAAAAAgAAAA4AAAABAAAAAgAAAAsAAAAOAAAAAwAAAA0AAAAHAAAAAwAAAA8AAAACAAAAAwAAABAAAAADAAAAAwAAABAAAAAAAAAAAwAAABcAAAAAAQAAAwAAAAwAAAAUAAAABAAAAA4AAAABAAAABAAAAAsAAAAOAAAAAwAAAA0AAAAFAAAAAwAAAA8AAAAEAAAAAwAAABAAAAADAAAAAwAAABAAAAAAAAAAAwAAABcAAAAQAQAAAwAAAAwAAAAVAAAAAwAAAA4AAAABAAAAAwAAAAsAAAAOAAAABQAAABIAAAAFAAAABQAAAA8AAAADAAAABQAAABAAAAAFAAAABQAAABAAAAAAAAAABQAAABcAAAAgAQAABQAAABMAAAAWAAAAAQAAAAsAAAAOAAAABQAAABIAAAAGAAAABQAAAA8AAAABAAAABQAAABAAAAAFAAAABQAAABAAAAAAAAAABQAAABcAAAAwAQAABQAAAAsAAAAOAAAABQAAABIAAAAHAAAABQAAAA8AAAACAAAABQAAABAAAAAFAAAABQAAABAAAAAAAAAABQAAABcAAABAAQAABQAAAAsAAAAOAAAABQAAABIAAAAIAAAABQAAAA8AAAAEAAAABQAAABAAAAAFAAAABQAAABAAAAAAAAAABQAAABcAAABQAQAABQAAAAsAAAAOAAAABQAAAA0AAAAPAAAABQAAAA8AAAADAAAABQAAABAAAAAFAAAABQAAABAAAAAAAAAABQAAABcAAABgAQAABQAAAAsAAAAOAAAABQAAABIAAAAKAAAABQAAAA8AAAABAAAABQAAABAAAAAFAAAABQAAABAAAAAAAAAABQAAABcAAABwAQAABQAAAAsAAAAOAAAABQAAAA0AAAANAAAABQAAAA8AAAACAAAABQAAABAAAAAFAAAABQAAABAAAAAAAAAABQAAABcAAACAAQAABQAAAAsAAAAOAAAABQAAABIAAAAMAAAABQAAAA8AAAAEAAAABQAAABAAAAAFAAAABQAAABAAAAAAAAAABQAAABcAAACQAQAABQAAAAsAAAAOAAAABQAAAA0AAAAMAAAABQAAAA8AAAADAAAABQAAABAAAAAFAAAABQAAABAAAAAAAAAABQAAABcAAACgAQAABQAAAAsAAAAOAAAABQAAAA0AAAALAAAABQAAAA8AAAABAAAABQAAABAAAAAFAAAABQAAABAAAAAAAAAABQAAABcAAACwAQAABQAAAAsAAAAOAAAABQAAAA0AAAAKAAAABQAAAA8AAAACAAAABQAAAAsAAAAOAAAAAgAAAA0AAAAGAAAAAgAAAA8AAAAEAAAAAgAAABAAAAAFAAAABQAAABAAAAAAAAAABQAAABcAAADAAQAABQAAABAAAAACAAAAAgAAABAAAAAAAAAAAgAAABcAAADQAQAAAgAAAAsAAAAOAAAAAgAAAA0AAAAIAAAAAgAAAA8AAAADAAAAAgAAAA0AAAAJAAAADgAAAA8AAAABAAAADgAAABAAAAACAAAAAgAAABAAAAAOAAAADgAAABAAAAAAAAAAAgAAABAAAAAAAAAADgAAABcAAADgAQAAAgAAABcAAADwAQAADgAAAAwAAAAXAAAAAAAAABcAAAAAAgAAAAAAAAwAAAAYAAAAAQAAABcAAAAQAgAAAQAAAAwAAAAZAAAAAgAAABcAAAAgAgAAAgAAAAwAAAAaAAAAAwAAABcAAAAwAgAAAwAAAAwAAAAbAAAABAAAABcAAABAAgAABAAAAAwAAAAcAAAABQAAABcAAABQAgAABQAAAAwAAAAdAAAABgAAABcAAABgAgAABgAAAAwAAAAeAAAADgAAABcAAABwAgAADgAAABcAAACAAgAAAAAAABcAAACQAgAAAQAAABcAAACgAgAAAgAAABcAAACwAgAAAwAAABcAAADAAgAABAAAABcAAADQAgAABQAAABcAAADgAgAABgAAABcAAADwAgAADgAAAAAAAACDJgAAAAAAAAMAAABTJwAACAAAAAEAAAAAAAAAAQAAAAIAAAC8AAAACQAAAAIAAABTAAAACAAAAAEAAAAIAAAAAgAAAAYAAABDAAAACAAAAAcAAAACAAAAAAAAAAgAAAAAAAAAAAAAAAkAAAAAAAAAAAAAAAAAAAAKAAAARAAAAAAAAAAIAAAAAQAAAAgAAAAAAAAABwAAAAAAAAABAAAACAAAAAEAAAABAAAACQAAAAAAAAABAAAAAQAAAAoAAABEAAAAAQAAAAEAAAABAAAACQAAAAAAAAAHAAAAAAAAAAIAAAAIAAAAAgAAAAIAAAAJAAAAAAAAAAIAAAACAAAACgAAAEQAAAACAAAAAgAAAAQAAAAAAAAAAAAAAAwAAAAfAAAAAwAAAAwAAAAgAAAABAAAAAwAAAAhAAAADgAAAAwAAAAiAAAACQAAAAwAAAAjAAAABgAAAAsAAAAHAAAADwAAAA0AAAADAAAADwAAAA4AAAABAAAADwAAAAsAAAAIAAAAAAAAAA0AAAAHAAAAAAAAAA8AAAAPAAAAAAAAABAAAAAAAAAAAAAAABAAAAACAAAAAAAAAAsAAAAAAAAADwAAABAAAAAEAAAADwAAAA8AAAAOAAAADwAAABAAAAAAAAAAAAAAAAsAAAAJAAAABQAAABEAAAAAAAAABQAAAA0AAAAGAAAABQAAABAAAAAPAAAABQAAABgAAACYawAABQAAAAUAAAAQAAAABAAAABAAAAADAAAABwAAABkAAAC7AwAAAAAAAH0oAAAAAAAAAwAAAI0oAAAIAAAAAQAAAAAAAAABAAAAAgAAAKoAAAAJAAAABQAAAGwAAAAJAAAAAQAAAAkAAAABAAAABwAAAAEAAAAAAAAACAAAAAAAAAAAAAAACQAAAAAAAAAAAAAAAAAAAAoAAABEAAAAAAAAAAAAAAABAAAACAAAAAEAAAAGAAAAKgAAAAgAAAABAAAACAAAAAAAAAAHAAAAAAAAAAEAAAAIAAAAAQAAAAEAAAAJAAAAAAAAAAEAAAABAAAACgAAAEQAAAABAAAAAQAAAAcAAAABAAAAAgAAAAgAAAACAAAAAgAAAAkAAAAAAAAAAgAAAAIAAAAKAAAARAAAAAIAAAAOAAAADAAAACQAAAACAAAADgAAAAEAAAACAAAACwAAAA4AAAADAAAAEgAAAAAAAAADAAAADwAAAAIAAAADAAAAEAAAAAMAAAADAAAAEAAAAAAAAAADAAAAFwAAAAAEAAADAAAADAAAACUAAAAEAAAADgAAAAEAAAAEAAAACwAAAA4AAAADAAAADAAAAAEAAAAGAAAADQAAAAYAAAADAAAADwAAAAQAAAADAAAAEAAAAAMAAAADAAAAEAAAAAAAAAADAAAAFwAAABAEAAADAAAACwAAAA4AAAADAAAADAAAAAUAAAAMAAAADQAAAAwAAAADAAAADwAAAAIAAAADAAAAEAAAAAMAAAADAAAAEAAAAAAAAAADAAAAFwAAACAEAAADAAAACwAAAA4AAAADAAAADAAAAAYAAAAMAAAADQAAAAwAAAADAAAADwAAAAQAAAADAAAAEAAAAAMAAAADAAAAEAAAAAAAAAADAAAAFwAAADAEAAADAAAADAAAACYAAAADAAAADgAAAAEAAAADAAAACwAAAA4AAAAFAAAADAAAAAcAAAAKAAAADQAAAAoAAAAFAAAADwAAAAMAAAAFAAAAEAAAAAUAAAAFAAAAEAAAAAAAAAAFAAAAFwAAAEAEAAAFAAAAEwAAACcAAAABAAAACwAAAA4AAAAFAAAADAAAAAgAAAAJAAAADQAAAAkAAAAFAAAADwAAAAEAAAAFAAAAEAAAAAUAAAAFAAAAEAAAAAAAAAAFAAAAFwAAAFAEAAAFAAAACwAAAA4AAAAFAAAADAAAAAkAAAALAAAADQAAAAsAAAAFAAAADwAAAAMAAAAFAAAAEAAAAAUAAAAFAAAAEAAAAAAAAAAFAAAAFwAAAGAEAAAFAAAACwAAAA4AAAAFAAAADAAAAAoAAAALAAAADQAAAAsAAAAFAAAADwAAAAEAAAAFAAAAEAAAAAUAAAAFAAAAEAAAAAAAAAAFAAAAFwAAAHAEAAAFAAAACwAAAA4AAAAFAAAADAAAAAsAAAANAAAADQAAAA0AAAAFAAAADwAAAAIAAAAFAAAAEAAAAAUAAAAFAAAAEAAAAAAAAAAFAAAAFwAAAIAEAAAFAAAACwAAAA4AAAAFAAAADAAAAAwAAAAIAAAADQAAAAgAAAAFAAAADwAAAAQAAAAFAAAAEAAAAAUAAAAFAAAAEAAAAAAAAAAFAAAAFwAAAJAEAAAFAAAACwAAAA4AAAAFAAAADAAAAA0AAAAPAAAADQAAAA8AAAAFAAAADwAAAAIAAAAFAAAACwAAAA4AAAACAAAADAAAAA4AAAAKAAAADQAAAAoAAAACAAAADwAAAAQAAAACAAAAEAAAAAUAAAAFAAAAEAAAAAAAAAAFAAAAFwAAAKAEAAAFAAAAEAAAAAIAAAACAAAAEAAAAAAAAAACAAAAFwAAALAEAAACAAAACwAAAA4AAAACAAAADAAAAA8AAAANAAAADQAAAA0AAAACAAAADwAAAAMAAAACAAAAEAAAAAIAAAACAAAAEAAAAAAAAAACAAAAFwAAAMAEAAACAAAACwAAAA4AAAACAAAADAAAABAAAAAHAAAADQAAAAcAAAACAAAADwAAAAEAAAACAAAAEAAAAAIAAAACAAAAEAAAAAAAAAACAAAAFwAAANAEAAACAAAACwAAAA4AAAACAAAADAAAABEAAAAFAAAADQAAAAUAAAACAAAADwAAAAMAAAACAAAADAAAABIAAAADAAAADQAAAAMAAAAOAAAADwAAAAEAAAAOAAAAEAAAAAIAAAACAAAAEAAAAA4AAAAOAAAAEAAAAAAAAAACAAAAEAAAAAAAAAAOAAAAFwAAAOAEAAACAAAAFwAAAPAEAAAOAAAADAAAACgAAAAAAAAAFwAAAAAFAAAAAAAAFwAAABAFAAAAAAAAFwAAACAFAAAAAAAAFwAAADAFAAAAAAAADAAAACkAAAABAAAAFwAAAEAFAAABAAAAFwAAAFAFAAABAAAAFwAAAGAFAAABAAAAFwAAAHAFAAABAAAAFwAAAIAFAAAAAAAAFwAAAJAFAAAAAAAAFwAAAKAFAAAAAAAAFwAAALAFAAAAAAAAFwAAAMAFAAABAAAAFwAAANAFAAABAAAAFwAAAOAFAAABAAAAFwAAAPAFAAABAAAAAAAAAEsnAAAAAAAAAwAAAIsoAAAIAAAAAQAAAAAAAAABAAAAAgAAAJwAAAAJAAAABQAAAGwAAAAJAAAAAQAAAAkAAAABAAAABwAAAAEAAAAAAAAACAAAAAAAAAAAAAAACQAAAAAAAAAAAAAAAAAAAAoAAABEAAAAAAAAAAAAAAABAAAACAAAAAEAAAAGAAAAHAAAAAgAAAABAAAACAAAAAAAAAAHAAAAAAAAAAEAAAAIAAAAAQAAAAEAAAAJAAAAAAAAAAEAAAABAAAACgAAAEQAAAABAAAAAgAAAAcAAAABAAAAAQAAAAgAAAABAAAAAQAAAAkAAAAAAAAAAQAAAAEAAAAKAAAARAAAAAEAAAABAAAADAAAACoAAAADAAAADgAAAAIAAAADAAAADAAAAAAAAAAEAAAADQAAAAEAAAAEAAAADwAAAAMAAAAEAAAAEAAAAAQAAAAEAAAAEAAAAAAAAAAEAAAAFwAAAAAGAAAEAAAADQAAAAEAAAAGAAAADwAAAAMAAAAGAAAAEAAAAAYAAAAGAAAAEAAAAAAAAAAGAAAAFwAAABAGAAAGAAAADAAAACsAAAAEAAAADgAAAAIAAAAEAAAADAAAAAUAAAAGAAAADQAAAAEAAAAGAAAADwAAAAQAAAAGAAAAEAAAAAYAAAAGAAAAEAAAAAAAAAAGAAAAFwAAACAGAAAGAAAADQAAAAEAAAAMAAAADwAAAAQAAAAMAAAAEAAAAAwAAAAMAAAAEAAAAAAAAAAMAAAAFwAAADAGAAAMAAAADAAAACwAAAAGAAAADgAAAAIAAAAGAAAADAAAAAcAAAAMAAAADQAAAAEAAAAMAAAADwAAAAYAAAAMAAAAEAAAAAwAAAAMAAAAEAAAAAAAAAAMAAAAFwAAAEAGAAAMAAAADQAAAAEAAAAJAAAADwAAAAYAAAAJAAAAEAAAAAkAAAAJAAAAEAAAAAAAAAAJAAAAFwAAAFAGAAAJAAAAEwAAAC0AAAACAAAADAAAAAkAAAAJAAAADQAAAAEAAAAJAAAADwAAAAIAAAAJAAAAEAAAAAkAAAAJAAAAEAAAAAAAAAAJAAAAFwAAAGAGAAAJAAAADQAAAAEAAAALAAAADwAAAAIAAAALAAAAEAAAAAsAAAALAAAAEAAAAAAAAAALAAAAFwAAAHAGAAALAAAADAAAAAsAAAAJAAAADQAAAAEAAAAJAAAADQAAAAEAAAAIAAAADwAAAAMAAAAJAAAADwAAAAMAAAAIAAAAEAAAAAkAAAAJAAAAEAAAAAAAAAAJAAAAFwAAAIAGAAAJAAAAEAAAAAgAAAAIAAAAEAAAAAAAAAAIAAAAFwAAAJAGAAAIAAAADQAAAAEAAAAPAAAADQAAAAEAAAAKAAAADwAAAAQAAAAPAAAADwAAAAQAAAAKAAAAEAAAAA8AAAAPAAAAEAAAAAAAAAAPAAAAFwAAAKAGAAAPAAAAEAAAAAoAAAAKAAAAEAAAAAAAAAAKAAAAFwAAALAGAAAKAAAADQAAAAEAAAANAAAADQAAAAEAAAAHAAAADwAAAAYAAAANAAAADwAAAAYAAAAHAAAAEAAAAA0AAAANAAAAEAAAAAAAAAANAAAAFwAAAMAGAAANAAAAEAAAAAcAAAAHAAAAEAAAAAAAAAAHAAAAFwAAANAGAAAHAAAADQAAAAEAAAAFAAAAEgAAABIAAAABAAAADwAAAAIAAAAFAAAADwAAAAIAAAABAAAAEAAAAAUAAAAFAAAAEAAAAAEAAAABAAAAEAAAAAAAAAAFAAAAEAAAAAAAAAABAAAAFwAAAOAGAAAFAAAAFwAAAPAGAAABAAAA"
    private const val CONSTS = "AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8AAQIDBAUGB/j5+vv8/f7/CAgICAgICAgICAgICAgICO7u7u7u7u7u7u7u7u7u7u4gISIjJCUmJygpKissLS4vMDEyMzQ1Njc4OTo7PD0+P0BBQkNERUZHSElKS0xNTk9QUVJTVFVWV1hZWltcXV5fYGFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6e3x9fn+AgYKDhIWGh4iJiouMjY6PkJGSk5SVlpeYmZqbnJ2en6ChoqOkpaanqKmqq6ytrq+wsbKztLW2t7i5uru8vb6/wMHCw8TFxsfIycrLzM3Oz9DR0tPU1dbX2Nna29zd3t/g4eLj5OXm5+jp6uvs7e7v8PHy8/T19vf4+fr7/P3+/wAAAgIEBAYGCAgKCgwMDg4QEBISFBQWFhgYGhocHB4eICAiIiQkJiYoKCoqLCwuLjAwMjI0NDY2ODg6Ojw8Pj6wsrS2sLK0tsDCxMbAwsTG0NLU1tDS1Nbg4uTm4OLk5nBydHZwcnR2gIKEhoCChIaQkpSWkJKUlqCipKagoqSmMDI0NjAyNDZAQkRGQEJERlBSVFZQUlRWYGJkZmBiZGbw8vT28PL09gACBAYAAgQGEBIUFhASFBYgIiQmICIkJhAQEBAQEBAQEBAQEBAQEBBxcXFxcXFxcXFxcXFxcXFxAwMDAwMDAwMDAwMDAwMDA/z8/Pz8/Pz8/Pz8/Pz8/Pz4+Pj4+Pj4+Pj4+Pj4+Pj4AAEAAQQFBAUAAQABBAUEBRAREBEUFRQVEBEQERQVFBVAQUBBREVERUBBQEFERURFUFFQUVRVVFVQUVBRVFVUVaakqqiurLKwpqSqqK6ssrAmJCooLiwyMCYkKiguLDIwAAECAwABAgMAAQIDAAECAyAhIiMgISIjICEiIyAhIiNAQUJDQEFCQ0BBQkNAQUJDYGFiY2BhYmNgYWJjYGFiYw=="

    /** Build the 7x256 P region (state+0x6898..0x6f98) for this state. */
    internal fun build(state: ByteArray): ByteArray {
        val p = ByteArray(0x700)
        val gpr = IntArray(6)
        val xmm = Array(16) { IntArray(16) }
        fun gr(r: Int): Int = if (r and 8 != 0) gpr[r and 7] and 0xff else gpr[r and 7]
        fun sr(r: Int, v: Int) {
            if (r and 8 != 0) gpr[r and 7] = (gpr[r and 7] and -256) or (v and 0xff)
            else gpr[r and 7] = v
        }
        var pc = 0
        while (pc < prog.size) {
            when (prog[pc]) {
                0 -> { sr(prog[pc + 2], state[prog[pc + 1]].toInt() and 0xff); pc += 3 }
                1 -> { sr(prog[pc + 2], gr(prog[pc + 1])); pc += 3 }
                2 -> { sr(prog[pc + 2], gr(prog[pc + 2]) xor prog[pc + 1]); pc += 3 }
                3 -> { sr(prog[pc + 2], gr(prog[pc + 2]) xor (state[prog[pc + 1]].toInt() and 0xff)); pc += 3 }
                4 -> {
                    val a = prog[pc + 1]; val b = prog[pc + 2]
                    sr(b, if (a == b) 0 else gr(b) xor gr(a)); pc += 3
                }
                5 -> { sr(prog[pc + 2], gr(prog[pc + 2]) + prog[pc + 1]); pc += 3 }
                6 -> { sr(prog[pc + 2], gr(prog[pc + 2]) and prog[pc + 1]); pc += 3 }
                7 -> {
                    val v = gr(prog[pc + 1]) and 0xff
                    val x = xmm[prog[pc + 2]]
                    for (i in 1 until 16) x[i] = 0
                    x[0] = v; pc += 3
                }
                8 -> {
                    val s = xmm[prog[pc + 1]]; val d = xmm[prog[pc + 2]]
                    for (i in 0..7) { d[2 * i] = s[i]; d[2 * i + 1] = s[i] }
                    pc += 3
                }
                9 -> {
                    val imm = prog[pc + 1]; val s = xmm[prog[pc + 2]]; val d = xmm[prog[pc + 3]]
                    val out = s.copyOf()
                    for (i in 0..3) {
                        val w = (imm shr (2 * i)) and 3
                        out[4 * i] = s[2 * w]; out[4 * i + 1] = s[2 * w + 1]
                    }
                    for (i in 0 until 16) d[i] = out[i]
                    pc += 4
                }
                10 -> {
                    val imm = prog[pc + 1]; val s = xmm[prog[pc + 2]]; val d = xmm[prog[pc + 3]]
                    val out = IntArray(16)
                    for (i in 0..3) {
                        val w = (imm shr (2 * i)) and 3
                        for (k in 0..3) out[4 * i + k] = s[4 * w + k]
                    }
                    for (i in 0 until 16) d[i] = out[i]
                    pc += 4
                }
                11 -> {
                    val s = xmm[prog[pc + 1]]; val d = xmm[prog[pc + 2]]
                    for (i in 0 until 16) d[i] = s[i]
                    pc += 3
                }
                12 -> {
                    val c = consts[prog[pc + 1]]; val d = xmm[prog[pc + 2]]
                    for (i in 0 until 16) d[i] = c[i].toInt() and 0xff
                    pc += 3
                }
                in 13..17 -> {
                    val a = xmm[prog[pc + 2]]; val b = xmm[prog[pc + 1]]
                    for (i in 0 until 16) a[i] = lane(prog[pc] - 13, a[i], b[i])
                    pc += 3
                }
                in 18..22 -> {
                    val c = consts[prog[pc + 1]]; val a = xmm[prog[pc + 2]]
                    for (i in 0 until 16) a[i] = lane(prog[pc] - 18, a[i], c[i].toInt() and 0xff)
                    pc += 3
                }
                23 -> {
                    val s = xmm[prog[pc + 2]]
                    for (i in 0 until 16) p[prog[pc + 1] + i] = s[i].toByte()
                    pc += 3
                }
                24 -> {
                    val off = prog[pc + 1] + gpr[4]
                    if (off >= 0x6898 && off < 0x6f98) {
                        val s = xmm[prog[pc + 2]]
                        for (i in 0 until 16) p[off - 0x6898 + i] = s[i].toByte()
                    }
                    pc += 3
                }
                25 -> pc = if (gpr[4] != 0x100) prog[pc + 1] else pc + 2
                else -> error("bad P-builder op ${prog[pc]} at $pc")
            }
        }
        return p
    }

    private fun lane(k: Int, x: Int, y: Int): Int = when (k) {
        0 -> x and y
        1 -> x or y
        2 -> x xor y
        3 -> (x + y) and 0xff
        else -> (x - y) and 0xff
    }
}
